dist: bionic
language: go
services:
  - memcached
  - redis-server
go:
  - 1.13.x
git:
  depth: 1
install:
  - GO111MODULE=off go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - golangci-lint run
  - MEMCACHED_HOST="localhost:11211" REDIS_HOST="localhost:6379" go test -tags integration -v -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
- bash <(curl -s https://codecov.io/bash)
