dist: bionic
language: go
env: GO111MODULE=on GOFLAGS='-mod vendor'
go:
  - 1.13.x
git:
  depth: 1
install:
  - GO111MODULE=off go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - golangci-lint run
  - go test -v -race ./...
